inherit_from: .rubocop_todo.yml

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Metrics/LineLength:
  Exclude:
    - 'config/**/*'

Rails:
  Enabled: true

Rails/OutputSafety:
  Enabled: false

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - '.bundle/**/*'
    - 'db/schema.rb'
    - 'config/deploy.rb'
